name: remote ssh command
on:
  release:
    types: [published]
jobs:
  deploy:
    name: Release
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.sha }}
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          envs: GITHUB_REF
          script: |
            whoami
            cd /root/kathena
            git fetch -p
            git checkout main && git reset --hard origin/main
            git checkout $GITHUB_REF
            yarn --ignore-engines
            yarn build --ignore-engines
            pm2 restart "kathena"
